# Generated by Django 4.2.10 on 2025-05-16 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='サイト名')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='サイトコード')),
                ('active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'サイト',
                'verbose_name_plural': 'サイト',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ConversionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='設定名')),
                ('css_class_prefix', models.CharField(blank=True, max_length=50, verbose_name='CSSクラスプレフィックス')),
                ('remove_empty_paragraphs', models.BooleanField(default=True, verbose_name='空の段落を削除')),
                ('preserve_images', models.BooleanField(default=True, verbose_name='画像を保持')),
                ('image_dir', models.CharField(blank=True, max_length=255, verbose_name='画像ディレクトリ')),
                ('active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversion_settings', to='api.site', verbose_name='サイト')),
            ],
            options={
                'verbose_name': '変換設定',
                'verbose_name_plural': '変換設定',
                'ordering': ['site', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ConversionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ルール名')),
                ('rule_type', models.CharField(choices=[('tag_replace', 'タグ置換'), ('class_add', 'クラス追加'), ('attribute_add', '属性追加'), ('custom', 'カスタム処理')], max_length=20, verbose_name='ルールタイプ')),
                ('source_selector', models.CharField(max_length=255, verbose_name='対象セレクタ')),
                ('target_value', models.CharField(blank=True, max_length=255, verbose_name='変換値')),
                ('priority', models.IntegerField(default=0, verbose_name='優先度')),
                ('active', models.BooleanField(default=True, verbose_name='有効')),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='api.conversionsetting', verbose_name='変換設定')),
            ],
            options={
                'verbose_name': '変換ルール',
                'verbose_name_plural': '変換ルール',
                'ordering': ['setting', 'priority'],
            },
        ),
    ]
