# Generated by Django 4.2.10 on 2025-06-20 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='サイト名')),
                ('url', models.CharField(blank=True, help_text='サイトのURL（英小文字）', max_length=100, unique=True, verbose_name='URL')),
                ('active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'サイト',
                'verbose_name_plural': 'サイト',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ConversionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='設定名')),
                ('css_class_prefix', models.CharField(blank=True, max_length=50, verbose_name='CSSクラスプレフィックス')),
                ('remove_empty_paragraphs', models.BooleanField(default=True, verbose_name='空の段落を削除')),
                ('preserve_images', models.BooleanField(default=True, verbose_name='画像を保持')),
                ('image_dir', models.CharField(blank=True, max_length=255, verbose_name='画像ディレクトリ')),
                ('active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversion_settings', to='api.site', verbose_name='サイト')),
            ],
            options={
                'verbose_name': '変換設定',
                'verbose_name_plural': '変換設定',
                'ordering': ['site', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ConversionOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('html_content', models.TextField()),
                ('html_path', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='api.conversionsetting')),
            ],
        ),
        migrations.CreateModel(
            name='ConversionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('タイトル', 'タイトル'), ('目次', '目次'), ('大見出し', '大見出し'), ('中見出し', '中見出し'), ('小見出し', '小見出し'), ('内部リンク', '内部リンク'), ('外部リンク', '外部リンク'), ('太字', '太字'), ('ハイライト', 'ハイライト'), ('赤字', '赤字'), ('箱の枠', '箱の枠'), ('箱内テキスト（中点）', '箱内テキスト（中点）'), ('箱内リンクテキスト（中点）', '箱内リンクテキスト（中点）'), ('箱内テキスト（番号）', '箱内テキスト（番号）'), ('表', '表'), ('テキスト', 'テキスト'), ('ショートコード', 'ショートコード'), ('文頭', '文頭'), ('文末', '文末')], default='大見出し', max_length=50, verbose_name='セクション')),
                ('tag', models.CharField(default='<p></p>', help_text='HTML形式で入力（例: <h1></h1>）', max_length=500, verbose_name='タグ')),
                ('word_style', models.CharField(choices=[('見出し１', '見出し１'), ('見出し２', '見出し２'), ('見出し３', '見出し３'), ('見出し４', '見出し４'), ('標準', '標準'), ('Wordに記載なし', 'Wordに記載なし')], default='標準', max_length=50, verbose_name='Wordにおけるスタイル')),
                ('bold', models.BooleanField(default=False, verbose_name='太字')),
                ('marker', models.BooleanField(default=False, verbose_name='マーカー')),
                ('prefix_text', models.CharField(blank=True, help_text='改行は￥nで入力', max_length=500, verbose_name='前にある文字列')),
                ('suffix_text', models.CharField(blank=True, help_text='改行は￥nで入力', max_length=500, verbose_name='後ろにある文字列')),
                ('active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='api.conversionsetting', verbose_name='変換設定')),
            ],
            options={
                'verbose_name': '変換ルール',
                'verbose_name_plural': '変換ルール',
                'ordering': ['setting', 'section'],
                'unique_together': {('setting', 'section')},
            },
        ),
    ]
