# Generated by Django 4.2.10 on 2025-07-09 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversionrule',
            name='split_on_period',
            field=models.BooleanField(default=False, help_text='句点（。）で段落を分割してタグを閉じる', verbose_name='句点で閉じる'),
        ),
    ]
