# Generated by Django 4.2.10 on 2025-07-16 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_client_domain'),
        ('api', '0002_conversionrule_split_on_period'),
    ]

    operations = [
    ]
