# Generated by Django 4.2.10 on 2025-05-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_conversionoutput'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='url',
            field=models.CharField(blank=True, help_text='サイトのURL（英小文字）', max_length=100, null=True, unique=True, verbose_name='URL'),
        ),
    ]
