# Generated by Django 4.2.10 on 2025-05-30 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_site_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='code',
        ),
    ]
