# Generated by Django 4.2.10 on 2025-07-18 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_client_domain_omit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversionrule',
            name='tag',
            field=models.CharField(default='<p></p>', help_text='HTML形式で入力（例: <h1></h1>）', max_length=10000, verbose_name='タグ'),
        ),
    ]
