# Generated by Django 4.2.10 on 2025-05-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_recreate_conversion_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversionrule',
            name='prefix_text',
            field=models.CharField(blank=True, help_text='改行は￥nで入力', max_length=500, null=True, verbose_name='前にある文字列'),
        ),
        migrations.AlterField(
            model_name='conversionrule',
            name='suffix_text',
            field=models.CharField(blank=True, help_text='改行は￥nで入力', max_length=500, null=True, verbose_name='後ろにある文字列'),
        ),
    ]
