# Generated by Django 4.2.10 on 2025-07-18 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_conversionrule_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversionrule',
            name='closing_tags',
            field=models.TextField(blank=True, help_text='大見出し・中見出しのセクション終了時に挿入する閉じタグ（例: </div></section>）', verbose_name='セクションの終わりに付ける閉じタグ'),
        ),
    ]
