# Generated by Django 4.2.10 on 2025-07-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_closing_tags_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversionrule',
            name='td_tag',
            field=models.TextField(blank=True, help_text='テーブルデータ用のHTMLタグ（例: <td style="...">{content}</td>）', verbose_name='tdタグ'),
        ),
        migrations.AddField(
            model_name='conversionrule',
            name='th_tag',
            field=models.TextField(blank=True, help_text='テーブルヘッダー用のHTMLタグ（例: <th style="...">{content}</th>）', verbose_name='thタグ'),
        ),
    ]
