# Generated by Django 4.2.10 on 2025-07-18 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_add_th_td_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversionrule',
            name='tag',
        ),
        migrations.AddField(
            model_name='conversionrule',
            name='table_tag',
            field=models.TextField(blank=True, help_text='テーブル全体のHTMLタグ（例: <table style="...">{content}</table>）', verbose_name='tableタグ'),
        ),
        migrations.AddField(
            model_name='conversionrule',
            name='tbody_tag',
            field=models.TextField(blank=True, help_text='tbodyのHTMLタグ（例: <tbody>{content}</tbody>）', verbose_name='tbodyタグ'),
        ),
        migrations.AddField(
            model_name='conversionrule',
            name='tr_tag',
            field=models.TextField(blank=True, help_text='trのHTMLタグ（例: <tr>{content}</tr>）', verbose_name='trタグ'),
        ),
        migrations.AlterField(
            model_name='conversionrule',
            name='td_tag',
            field=models.TextField(blank=True, help_text='tdのHTMLタグ（例: <td style="...">{content}</td>）', verbose_name='tdタグ'),
        ),
        migrations.AlterField(
            model_name='conversionrule',
            name='th_tag',
            field=models.TextField(blank=True, help_text='thのHTMLタグ（例: <th style="...">{content}</th>）', verbose_name='thタグ'),
        ),
    ]
