# Generated by Django 4.2.10 on 2025-07-18 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_table_tag_refactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversionrule',
            name='tag',
            field=models.TextField(blank=True, help_text='HTMLタグ（例: <h2>{content}</h2> など）', verbose_name='タグ'),
        ),
    ]
