# Generated by Django 4.2.10 on 2025-07-23 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_add_tag_field_to_conversionrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='use_bullet_points',
            field=models.BooleanField(default=True, help_text='中点（・）を除去してliタグでリスト表示する', verbose_name='中点を除去してliタグを使う'),
        ),
        migrations.AlterField(
            model_name='conversionrule',
            name='section',
            field=models.CharField(choices=[('タイトル', 'タイトル'), ('目次', '目次'), ('大見出し', '大見出し'), ('中見出し', '中見出し'), ('小見出し', '小見出し'), ('内部リンク', '内部リンク'), ('外部リンク', '外部リンク'), ('太字', '太字'), ('ハイライト', 'ハイライト'), ('赤字', '赤字'), ('箱の枠', '箱の枠'), ('箱内リンクテキスト', '箱内リンクテキスト'), ('箱内テキスト（中点）', '箱内テキスト（中点）'), ('箱内リンクテキスト（中点）', '箱内リンクテキスト（中点）'), ('箱内テキスト（番号）', '箱内テキスト（番号）'), ('表', '表'), ('テキスト', 'テキスト'), ('ショートコード', 'ショートコード'), ('文頭', '文頭'), ('文末', '文末')], default='大見出し', max_length=50, verbose_name='セクション'),
        ),
    ]
