# Generated by Django 4.2.10 on 2025-08-13 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_site_use_bullet_points_alter_conversionrule_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversionrule',
            name='use_bullet_points',
            field=models.BooleanField(default=False, help_text='表のセル内で中点（・）を除去してul/liタグでリスト表示する', verbose_name='中点を除去してul/liタグを使う'),
        ),
    ]
