# Generated by Django 4.2.10 on 2025-08-13 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_conversionrule_use_bullet_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversionrule',
            name='table_convert_bullets_to_ul',
            field=models.BooleanField(default=False, help_text='表のセル内で中点（・）を除去してul/liタグでリスト表示する（表専用）', verbose_name='表で中点をul/liタグに変換'),
        ),
    ]
